from enum import Enum


class ReasonID(str, Enum):
    # === VALIDATION FAILURES ===
    INVALID_ENVELOPE = "INVALID_ENVELOPE"
    INVALID_OUTPUT = "INVALID_OUTPUT"
    SCHEMA_VIOLATION = "SCHEMA_VIOLATION"
    MISSING_REQUIRED_FIELD = "MISSING_REQUIRED_FIELD"

    # === CANONICALIZATION / HASHING ===
    CANONICALIZATION_FAILED = "CANONICALIZATION_FAILED"
    HASHING_FAILED = "HASHING_FAILED"

    # === POLICY ===
    POLICY_DENIED = "POLICY_DENIED"
    UNSUPPORTED_TASK = "UNSUPPORTED_TASK"
    UNSUPPORTED_MODEL = "UNSUPPORTED_MODEL"

    # === DETERMINISM ===
    NON_DETERMINISTIC_OUTPUT = "NON_DETERMINISTIC_OUTPUT"

    # === ADAPTER ===
    ADAPTER_NOT_REGISTERED = "ADAPTER_NOT_REGISTERED"
    ADAPTER_VALIDATION_FAILED = "ADAPTER_VALIDATION_FAILED"

    # === INTERNAL ===
    INTERNAL_ERROR = "INTERNAL_ERROR"
